/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-02-02 05:30:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.useJavaBean;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Title</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h3>useJavaBean Test</h3>\n");
      out.write("\n");
      out.write("\n");
      out.write("javaBean:customer1 <br>\n");
      out.write('\n');
      com.ljs.test.useJavaBean.Customer customer1 = null;
      customer1 = (com.ljs.test.useJavaBean.Customer) _jspx_page_context.getAttribute("customer1", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (customer1 == null){
        customer1 = new com.ljs.test.useJavaBean.Customer();
        _jspx_page_context.setAttribute("customer1", customer1, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("customer1"), "age", "11", null, null, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("customer1"), "name", "newCustomer11", null, null, false);
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("name：");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer1")).getName())));
      out.write(" <br>\n");
      out.write("age：");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer1")).getAge())));
      out.write(" <br>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("javaBean:customer2 <br>\n");
      out.write("\n");
      com.ljs.test.useJavaBean.Customer customer2 = null;
      customer2 = (com.ljs.test.useJavaBean.Customer) _jspx_page_context.getAttribute("customer2", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (customer2 == null){
        customer2 = new com.ljs.test.useJavaBean.Customer();
        _jspx_page_context.setAttribute("customer2", customer2, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("customer2"), request);
      out.write("\n");
      out.write("\n");
      out.write("id:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer2")).getId())));
      out.write("<br>\n");
      out.write("name:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer2")).getName())));
      out.write("<br>\n");
      out.write("age:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer2")).getAge())));
      out.write("<br>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("javaBean:customer3 <br>\n");
      out.write('\n');
      com.ljs.test.useJavaBean.Customer customer3 = null;
      customer3 = (com.ljs.test.useJavaBean.Customer) _jspx_page_context.getAttribute("customer3", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (customer3 == null){
        try {
          customer3 = (com.ljs.test.useJavaBean.Customer) java.beans.Beans.instantiate(this.getClass().getClassLoader(), "com.ljs.test.useJavaBean.Customer");
        } catch (java.lang.ClassNotFoundException exc) {
          throw new InstantiationException(exc.getMessage());
        } catch (java.lang.Exception exc) {
          throw new javax.servlet.ServletException("Cannot create bean of class " + "com.ljs.test.useJavaBean.Customer", exc);
        }
        _jspx_page_context.setAttribute("customer3", customer3, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("customer3"), "age", "33", null, null, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("customer3"), "name", "newCustomer33", null, null, false);
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("name：");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer3")).getName())));
      out.write(" <br>\n");
      out.write("age：");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.ljs.test.useJavaBean.Customer)_jspx_page_context.findAttribute("customer3")).getAge())));
      out.write(" <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("javaBean:customer4 <br>\n");
      out.write('\n');
      java.lang.Object customer4 = null;
      customer4 = (java.lang.Object) _jspx_page_context.getAttribute("customer4", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (customer4 == null){
        try {
          customer4 = (java.lang.Object) java.beans.Beans.instantiate(this.getClass().getClassLoader(), "com.ljs.test.useJavaBean.Customer");
        } catch (java.lang.ClassNotFoundException exc) {
          throw new InstantiationException(exc.getMessage());
        } catch (java.lang.Exception exc) {
          throw new javax.servlet.ServletException("Cannot create bean of class " + "com.ljs.test.useJavaBean.Customer", exc);
        }
        _jspx_page_context.setAttribute("customer4", customer4, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
