@startuml

abstract class Duck{
    + quack():void
    + swim():void
    + fly(): void
}

class WildDuck{

}

class BeijingDuck{

}

class ToyDuck{

}

Duck <|-- WildDuck
Duck <|-- BeijingDuck
Duck <|-- ToyDuck
@enduml